server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.207.221:8848 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'


